/**
 * Conversation persistence types following v1.0.0 schema
 */

import type { ChatModelOptions } from './chat.types.js';

/**
 * Provider type for conversations
 */
export type ConversationProvider = 'openai' | 'anthropic' | 'custom';

/**
 * Conversation reference in index (lightweight)
 */
export interface ConversationRef {
  /** Unique conversation ID */
  id: string;

  /** Relative path to conversation file (e.g., "2025-01-03/d4e5f6.json") */
  path: string;

  /** Conversation title (derived from first user message) */
  title: string;

  /** Optional agent ID if using an agent */
  agentId?: string;

  /** Model used for this conversation */
  model: string;

  /** Number of messages in conversation */
  messageCount: number;

  /** Creation timestamp (ISO 8601) */
  createdAt: string;

  /** Last update timestamp (ISO 8601) */
  updatedAt: string;

  /** Tags for categorization/search */
  tags?: string[];

  /** Pinned conversations appear first in list */
  isPinned?: boolean;
}

/**
 * Index file structure
 */
export interface ConversationIndex {
  /** Schema version for migrations */
  version: number;

  /** Array of conversation references */
  conversations: ConversationRef[];

  /** Last index update timestamp */
  updatedAt?: string;
}

/**
 * Reference/attachment in user message
 */
export interface Reference {
  /** Reference type */
  type: 'file' | 'selection' | 'image';

  /** Resource URI */
  uri: string;

  /** Inline content (for small files/selections) */
  content?: string;

  /** Selection range (for code selections) */
  range?: {
    start: number;
    end: number;
  };

  /** MIME type (for images) */
  mimeType?: string;

  /** Display name */
  name?: string;
}

/**
 * Tool call in assistant message (OpenAI-compatible format)
 */
export interface ToolCall {
  /** Tool call ID (generated by model or backend) */
  id: string;

  /** Type (always 'function' for OpenAI compatibility) */
  type: 'function';

  /** Function call details */
  function: {
    /** Function/tool name */
    name: string;

    /** JSON-encoded arguments string */
    arguments: string;
  };

  /** UI state (not sent to API, Agentage extension) */
  status?: 'pending' | 'running' | 'completed' | 'error';
}

/**
 * User message in conversation (OpenAI-compatible)
 */
export interface UserMessage {
  /** Message role (OpenAI format) */
  role: 'user';

  /** Unique message ID (for UI correlation, Agentage extension) */
  id: string;

  /** User's text prompt */
  content: string;

  /** ISO 8601 timestamp (Agentage extension) */
  timestamp: string;

  /** Optional identifier for multi-user scenarios */
  name?: string;

  /** Attached references - called 'attachments' in spec (files, selections, images) */
  attachments?: Attachment[];

  /** Model configuration at time of message (optional, Agentage extension) */
  config?: {
    model?: string;
    temperature?: number;
    maxTokens?: number;
  };
}

/**
 * Attachment in user message (Agentage extension of OpenAI format)
 */
export interface Attachment {
  /** Attachment type */
  type: 'file' | 'image' | 'selection';

  /** Resource URI */
  uri: string;

  /** Display name */
  name?: string;

  /** Inline content (for small files/selections) */
  content?: string;

  /** Selection range (for code selections) */
  range?: {
    start: number;
    end: number;
  };

  /** MIME type (for images) */
  mimeType?: string;
}

/**
 * Assistant message in conversation (OpenAI-compatible)
 */
export interface AssistantMessage {
  /** Message role (OpenAI format) */
  role: 'assistant';

  /** Unique message ID (Agentage extension) */
  id: string;

  /** Assistant's text response (may be null if only tool calls or refusal) */
  content: string | null;

  /** ISO 8601 timestamp (Agentage extension) */
  timestamp: string;

  /** Tool calls made by assistant (OpenAI format) */
  tool_calls?: ToolCall[];

  /** Refusal message if assistant declined to respond (OpenAI format) */
  refusal?: string | null;

  /** Thinking/reasoning text (Anthropic extended thinking, provider extension) */
  _anthropic?: {
    thinking?: string;
    stopReason?: 'end_turn' | 'max_tokens' | 'stop_sequence' | 'tool_use';
  };

  /** OpenAI-specific extensions */
  _openai?: {
    finishReason?: 'stop' | 'length' | 'tool_calls' | 'content_filter';
  };
}

/**
 * Tool message in conversation (OpenAI-compatible)
 */
export interface ToolMessage {
  /** Message role (OpenAI format) */
  role: 'tool';

  /** Unique message ID (Agentage extension) */
  id: string;

  /** Tool execution result (typically JSON string) */
  content: string;

  /** ISO 8601 timestamp (Agentage extension) */
  timestamp: string;

  /** Tool call ID this result corresponds to (must match assistant's tool_calls[].id) */
  tool_call_id: string;

  /** Tool name (optional, for validation/debugging) */
  name?: string;

  /** Whether execution failed (Agentage extension) */
  isError?: boolean;

  /** Duration in milliseconds (Agentage extension, for debugging) */
  duration?: number;
}

/**
 * Union type for all message types
 */
export type ConversationMessage = UserMessage | AssistantMessage | ToolMessage;

/**
 * Session configuration for conversation
 */
export interface SessionConfig {
  /** Model identifier (e.g., 'claude-sonnet-4-20250514', 'gpt-4o') */
  model: string;

  /** Model provider (for UI display) */
  provider: ConversationProvider;

  /** System prompt/instructions */
  system?: string;

  /** Agent ID (if using predefined agent) */
  agentId?: string;

  /** Agent name (for display) */
  agentName?: string;

  /** Enabled tool IDs */
  tools?: string[];

  /** Model parameters */
  modelConfig?: ChatModelOptions;
}

/**
 * Conversation metadata
 */
export interface ConversationMetadata {
  /** Creation timestamp */
  createdAt: string;

  /** Last update timestamp */
  updatedAt: string;

  /** User-assigned tags */
  tags?: string[];

  /** Pinned status */
  isPinned?: boolean;

  /** Workspace path (if applicable) */
  workspace?: string;

  /** Original export source (if imported) */
  exportedFrom?: {
    app: string;
    version: string;
    timestamp: string;
  };
}

/**
 * Usage statistics
 */
export interface UsageStats {
  /** Total input tokens */
  inputTokens: number;

  /** Total output tokens */
  outputTokens: number;

  /** Total tokens (input + output) */
  totalTokens: number;

  /** Per-model breakdown */
  byModel?: Record<
    string,
    {
      inputTokens: number;
      outputTokens: number;
    }
  >;
}

/**
 * Full conversation snapshot stored in date folder (v1.0.0 schema)
 */
export interface ConversationSnapshot {
  /** Schema version for migrations */
  version: string; // "1.0.0"

  /** Format type identifier */
  format: 'agentage-conversation';

  /** Unique conversation ID */
  id: string;

  /** Human-readable title (derived from first user message) */
  title: string;

  /** Session configuration */
  session: SessionConfig;

  /** Message history */
  messages: ConversationMessage[];

  /** Conversation metadata */
  metadata: ConversationMetadata;

  /** Usage statistics */
  usage?: UsageStats;
}

/**
 * Options for creating a new conversation
 */
export interface CreateConversationOptions {
  /** Optional conversation ID (if not provided, will be auto-generated) */
  id?: string;

  /** Optional agent ID */
  agentId?: string;

  /** Optional agent name */
  agentName?: string;

  /** System prompt */
  system: string;

  /** Model identifier */
  model: string;

  /** Model provider */
  provider: ConversationProvider;

  /** Optional title (defaults to "New conversation") */
  title?: string;

  /** Optional tags */
  tags?: string[];

  /** Enabled tools */
  tools?: string[];

  /** Model configuration */
  modelConfig?: ChatModelOptions;
}

/**
 * Options for listing conversations
 */
export interface ListConversationsOptions {
  /** Filter by agent ID */
  agentId?: string;

  /** Filter by model */
  model?: string;

  /** Filter by tags */
  tags?: string[];

  /** Search in titles */
  search?: string;

  /** Include pinned first */
  pinnedFirst?: boolean;

  /** Sort order */
  sortBy?: 'createdAt' | 'updatedAt' | 'messageCount';

  /** Sort direction */
  sortDirection?: 'asc' | 'desc';

  /** Pagination: skip N items */
  skip?: number;

  /** Pagination: limit results */
  limit?: number;
}

/**
 * Conversation metadata update
 */
export interface UpdateConversationMetadata {
  title?: string;
  tags?: string[];
  isPinned?: boolean;
}
