/**
 * Conversation persistence types following v1.0.0 schema
 */

import type { ChatModelOptions } from './chat.types.js';

/**
 * Provider type for conversations
 */
export type ConversationProvider = 'openai' | 'anthropic' | 'custom';

/**
 * Conversation reference in index (lightweight)
 */
export interface ConversationRef {
  /** Unique conversation ID */
  id: string;

  /** Relative path to conversation file (e.g., "2025-01-03/d4e5f6.json") */
  path: string;

  /** Conversation title (derived from first user message) */
  title: string;

  /** Optional agent ID if using an agent */
  agentId?: string;

  /** Model used for this conversation */
  model: string;

  /** Number of messages in conversation */
  messageCount: number;

  /** Creation timestamp (ISO 8601) */
  createdAt: string;

  /** Last update timestamp (ISO 8601) */
  updatedAt: string;

  /** Tags for categorization/search */
  tags?: string[];

  /** Pinned conversations appear first in list */
  isPinned?: boolean;
}

/**
 * Index file structure
 */
export interface ConversationIndex {
  /** Schema version for migrations */
  version: number;

  /** Array of conversation references */
  conversations: ConversationRef[];

  /** Last index update timestamp */
  updatedAt?: string;
}

/**
 * Reference/attachment in user message
 */
export interface Reference {
  /** Reference type */
  type: 'file' | 'selection' | 'image';

  /** Resource URI */
  uri: string;

  /** Inline content (for small files/selections) */
  content?: string;

  /** Selection range (for code selections) */
  range?: {
    start: number;
    end: number;
  };

  /** MIME type (for images) */
  mimeType?: string;

  /** Display name */
  name?: string;
}

/**
 * Tool call in assistant message
 */
export interface ToolCall {
  /** Tool call ID (generated by model or backend) */
  id: string;

  /** Tool name */
  name: string;

  /** Tool input parameters (JSON-serializable) */
  input: unknown;

  /** UI state (not sent to API) */
  status?: 'pending' | 'running' | 'completed' | 'error';
}

/**
 * User message in conversation
 */
export interface UserMessage {
  /** Message type */
  type: 'user';

  /** Unique message ID (for UI correlation) */
  id: string;

  /** User's text prompt */
  content: string;

  /** ISO 8601 timestamp */
  timestamp: string;

  /** Attached references (files, selections, images) */
  references?: Reference[];

  /** Model configuration at time of message (optional) */
  config?: {
    model?: string;
    temperature?: number;
    maxTokens?: number;
  };
}

/**
 * Assistant message in conversation
 */
export interface AssistantMessage {
  /** Message type */
  type: 'assistant';

  /** Unique message ID */
  id: string;

  /** Assistant's text response (may be empty if only tool calls) */
  content: string;

  /** ISO 8601 timestamp */
  timestamp: string;

  /** Stop reason (why response ended) */
  finishReason?:
    | 'end_turn'
    | 'max_tokens'
    | 'stop_sequence'
    | 'pause_turn'
    | 'refusal'
    | 'tool_use';

  /** Thinking/reasoning text (Claude extended thinking) */
  thinking?: string;

  /** Tool calls made by assistant (only present when finishReason is 'tool_use') */
  tool_calls?: ToolCall[];
}

/**
 * Tool message in conversation
 */
export interface ToolMessage {
  /** Message type */
  type: 'tool';

  /** Unique message ID */
  id: string;

  /** Tool execution result (JSON string) */
  content: string;

  /** ISO 8601 timestamp */
  timestamp: string;

  /** Tool call ID this result corresponds to */
  tool_call_id: string;

  /** Tool name (for validation) */
  name: string;

  /** Whether execution failed */
  isError?: boolean;

  /** Duration in milliseconds (for debugging) */
  duration?: number;
}

/**
 * Union type for all message types
 */
export type ConversationMessage = UserMessage | AssistantMessage | ToolMessage;

/**
 * Session configuration for conversation
 */
export interface SessionConfig {
  /** Model identifier (e.g., 'claude-sonnet-4-20250514', 'gpt-4o') */
  model: string;

  /** Model provider (for UI display) */
  provider: ConversationProvider;

  /** System prompt/instructions */
  system?: string;

  /** Agent ID (if using predefined agent) */
  agentId?: string;

  /** Agent name (for display) */
  agentName?: string;

  /** Enabled tool IDs */
  tools?: string[];

  /** Model parameters */
  modelConfig?: ChatModelOptions;
}

/**
 * Conversation metadata
 */
export interface ConversationMetadata {
  /** Creation timestamp */
  createdAt: string;

  /** Last update timestamp */
  updatedAt: string;

  /** User-assigned tags */
  tags?: string[];

  /** Pinned status */
  isPinned?: boolean;

  /** Workspace path (if applicable) */
  workspace?: string;

  /** Original export source (if imported) */
  exportedFrom?: {
    app: string;
    version: string;
    timestamp: string;
  };
}

/**
 * Usage statistics
 */
export interface UsageStats {
  /** Total input tokens */
  inputTokens: number;

  /** Total output tokens */
  outputTokens: number;

  /** Total tokens (input + output) */
  totalTokens: number;

  /** Per-model breakdown */
  byModel?: Record<
    string,
    {
      inputTokens: number;
      outputTokens: number;
    }
  >;
}

/**
 * Full conversation snapshot stored in date folder (v1.0.0 schema)
 */
export interface ConversationSnapshot {
  /** Schema version for migrations */
  version: string; // "1.0.0"

  /** Format type identifier */
  format: 'agentage-conversation';

  /** Unique conversation ID */
  id: string;

  /** Human-readable title (derived from first user message) */
  title: string;

  /** Session configuration */
  session: SessionConfig;

  /** Message history */
  messages: ConversationMessage[];

  /** Conversation metadata */
  metadata: ConversationMetadata;

  /** Usage statistics */
  usage?: UsageStats;
}

/**
 * Options for creating a new conversation
 */
export interface CreateConversationOptions {
  /** Optional conversation ID (if not provided, will be auto-generated) */
  id?: string;

  /** Optional agent ID */
  agentId?: string;

  /** Optional agent name */
  agentName?: string;

  /** System prompt */
  system: string;

  /** Model identifier */
  model: string;

  /** Model provider */
  provider: ConversationProvider;

  /** Optional title (defaults to "New conversation") */
  title?: string;

  /** Optional tags */
  tags?: string[];

  /** Enabled tools */
  tools?: string[];

  /** Model configuration */
  modelConfig?: ChatModelOptions;
}

/**
 * Options for listing conversations
 */
export interface ListConversationsOptions {
  /** Filter by agent ID */
  agentId?: string;

  /** Filter by model */
  model?: string;

  /** Filter by tags */
  tags?: string[];

  /** Search in titles */
  search?: string;

  /** Include pinned first */
  pinnedFirst?: boolean;

  /** Sort order */
  sortBy?: 'createdAt' | 'updatedAt' | 'messageCount';

  /** Sort direction */
  sortDirection?: 'asc' | 'desc';

  /** Pagination: skip N items */
  skip?: number;

  /** Pagination: limit results */
  limit?: number;
}

/**
 * Conversation metadata update
 */
export interface UpdateConversationMetadata {
  title?: string;
  tags?: string[];
  isPinned?: boolean;
}
